ElectricStore/Areas/Admin/Controllers/BrandController.cs
using ElectricStore.DataAccess.IRepository;
using ElectricStore.Models.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ElectricStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class BrandController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        public BrandController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult>Upsert(int? id)
        {
            Brand brand = new Brand();
            if(id==null)
            {
                return View(brand);
            }
            else
            {
                brand = await _unitOfWork.Brand.GetAsync(id.GetValueOrDefault());
                if(brand ==null)
                {
                    return NotFound();
                }
                return View(brand);
            }
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Upsert(Brand brand)
        {
            if(ModelState.IsValid)
            {
                if(brand.Id==0)
                {
                    await _unitOfWork.Brand.AddAsync(brand);
                    TempData["message"] = "Created Successfully";
                }
                else
                {
                    await _unitOfWork.Brand.UpdateAsync(brand);
                    TempData["message"] = "Updated Successfully";
                }
                await _unitOfWork.SaveAsync();
                return RedirectToAction(nameof(Index));
            }
            return View();
        }
        #region  Api
        public async Task<IActionResult>GetAll()
        {
            var brandList = await _unitOfWork.Brand.GetAllAsync();
            return Json(new { Data = brandList });
        }
        [HttpDelete]
        public async Task<IActionResult>Delete(int id)
        {
            var brandObj = await _unitOfWork.Brand.GetAsync(id);
            if(brandObj==null)
            {
                return Json(new { success = false, message = "Error While Deleting" });
            }
            await _unitOfWork.Brand.RemoveAsync(brandObj);
            await _unitOfWork.SaveAsync();
            return Json(new { success = true, message = "Deleted Successfully" });
        }
        #endregion
    }
}

ElectricStore/Areas/Admin/Controllers/ProductController.cs
using ElectricStore.Data;
using ElectricStore.DataAccess.IRepository;
using ElectricStore.Models.Models;
using ElectricStore.Models.ViewModels;
using ElectricStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ElectricStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class ProductController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnveronment;
        public ProductController(IUnitOfWork unitOfWork,IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnveronment = webHostEnvironment;
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }
        public async Task<IActionResult>Upsert(int? id)
        {
            var catList = await _unitOfWork.Category.GetAllAsync();
            var brandList = await _unitOfWork.Brand.GetAllAsync();
            ProductVM productVM = new ProductVM()
            {
                Product = new Product(),
                CategoryList = catList.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                }),
                BrandList = brandList.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                })
            };
            if(id==null)
            {
                return View(productVM);
            }
            else
            {
                productVM.Product = await _unitOfWork.Product.GetAsync(id.GetValueOrDefault());
                if(productVM.Product==null)
                {
                    return NotFound();
                }
                return View(productVM);
            }
            
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult>Upsert(ProductVM productVM)
        {
            if(ModelState.IsValid)
            {
                var webRootPath = _webHostEnveronment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if(files.Count()>0)
                {
                    var fileName = Guid.NewGuid().ToString();
                    var upload = Path.Combine(webRootPath, @"Photos\Products");
                    var extension = Path.GetExtension(files[0].FileName);
                    if(productVM.Product.Id!=0)
                    {
                        var productObj = await _unitOfWork.Product.GetAsync(productVM.Product.Id);
                        if(productObj!=null)
                        {
                            var imageData = Path.Combine(webRootPath, productObj.ImageUrl.TrimStart('\\'));
                            if(System.IO.File.Exists(imageData))
                            {
                                System.IO.File.Delete(imageData);
                            }
                        }
                    }
                    using(var fileStream=new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                    {
                        await files[0].CopyToAsync(fileStream);
                    }
                    productVM.Product.ImageUrl = SD.imagePath + fileName + extension;

                }
                else
                {
                    if(productVM.Product.Id!=0)
                    {
                        var productObj = await _unitOfWork.Product.GetAsync(productVM.Product.Id);
                        if (productVM.Product == null)
                        {
                            return NotFound();
                        }
                        productVM.Product.ImageUrl = productObj.ImageUrl;
                    }
                   
                }
                if(productVM.Product.Id!=0)
                {
                    await _unitOfWork.Product.UpdateAsync(productVM.Product);
                    TempData["message"] = "Updated Successfully";
                }
                else
                {
                    await _unitOfWork.Product.AddAsync(productVM.Product);
                    TempData["message"] = "Created Successfully";
                }
                await _unitOfWork.SaveAsync();
                return RedirectToAction(nameof(Index));

            }
            else
            {
                var catList = await _unitOfWork.Category.GetAllAsync();
                var brandList = await _unitOfWork.Brand.GetAllAsync();
                productVM.CategoryList = catList.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
                productVM.BrandList = brandList.Select(x => new SelectListItem
                {
                    Text = x.Name,
                    Value = x.Id.ToString()
                });
                if(productVM.Product.Id!=0)
                {
                    productVM.Product = await _unitOfWork.Product.GetAsync(productVM.Product.Id);

                }
                return View(productVM);

            }
        }
        #region Api
        public async Task<IActionResult>GetAll()
        {
            var productList = await _unitOfWork.Product.GetAllAsync(includeProperties:"Category,Brand");
            return Json(new { Data = productList });
        }
        [HttpDelete]
        public async Task<IActionResult>Delete(int id)
        {
            var productObj = await _unitOfWork.Product.GetAsync(id);
            if(productObj==null)
            {
                return Json(new { success = false, message = "Error While Deleting" });
            }
            var webRootPath = _webHostEnveronment.WebRootPath;
            var imageData = Path.Combine(webRootPath, productObj.ImageUrl.TrimStart('\\'));
            if(System.IO.File.Exists(imageData))
            {
                System.IO.File.Delete(imageData);
            }
            await _unitOfWork.Product.RemoveAsync(productObj);
            await _unitOfWork.SaveAsync();
            return Json(new { success = true, message = "Deleted Successfully" });
        }
        #endregion
    }
}

ElectricStore/Areas/Admin/Controllers/SliderController.cs
using ElectricStore.DataAccess.IRepository;
using ElectricStore.Models.Models;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Hosting;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;

namespace ElectricStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class SliderController : Controller
    {
        private readonly IUnitOfWork _unitOfWork;
        private readonly IWebHostEnvironment _webHostEnveronment;
        public SliderController(IUnitOfWork unitOfWork, IWebHostEnvironment webHostEnvironment)
        {
            _unitOfWork = unitOfWork;
            _webHostEnveronment = webHostEnvironment;
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Upsert(int? id)
        {
            ImageSlider imageSlider = new ImageSlider();
            if (id == null)
            {
                return View(imageSlider);
            }
            else
            {
                imageSlider = await _unitOfWork.ImageSlider.GetAsync(id.GetValueOrDefault());
                if (imageSlider == null)
                {
                    return NotFound();
                }
                return View(imageSlider);
            }
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Upsert(ImageSlider imageSlider)
        {
            if (ModelState.IsValid)
            {
                var webRootPath = _webHostEnveronment.WebRootPath;
                var files = HttpContext.Request.Form.Files;
                if (files.Count() > 0)
                {
                    var fileName = Guid.NewGuid().ToString();
                    var upload = Path.Combine(webRootPath, @"Photos\Slider");
                    var extension = Path.GetExtension(files[0].FileName);
                    if (imageSlider.Id != 0)
                    {
                        var imageSliderObj = await _unitOfWork.ImageSlider.GetAsync(imageSlider.Id);
                        if (imageSliderObj != null)
                        {
                            var imageData = Path.Combine(webRootPath, imageSliderObj.ImageUrl.TrimStart('\\'));
                            if (System.IO.File.Exists(imageData))
                            {
                                System.IO.File.Delete(imageData);
                            }
                        }
                    }
                    using (var fileStream = new FileStream(Path.Combine(upload, fileName + extension), FileMode.Create))
                    {
                        await files[0].CopyToAsync(fileStream);
                    }
                    imageSlider.ImageUrl = @"\Photos\Slider\" + fileName + extension;

                }
                else
                {
                    if (imageSlider.Id != 0)
                    {
                        var imageSliderObj = await _unitOfWork.ImageSlider.GetAsync(imageSlider.Id);
                        if (imageSliderObj == null)
                        {
                            return NotFound();
                        }
                        imageSlider.ImageUrl = imageSliderObj.ImageUrl;
                    }

                }
                if (imageSlider.Id != 0)
                {
                    await _unitOfWork.ImageSlider.UpdateAsync(imageSlider);
                    TempData["message"] = "Updated Successfully";
                }
                else
                {
                    await _unitOfWork.ImageSlider.AddAsync(imageSlider);
                    TempData["message"] = "Created Successfully";
                }
                await _unitOfWork.SaveAsync();
                return RedirectToAction(nameof(Index));

            }
            return View();
        }
        #region Api
        public async Task<IActionResult> GetAll()
        {
            var imageSliderList = await _unitOfWork.ImageSlider.GetAllAsync();
            return Json(new { Data = imageSliderList });
        }
        [HttpDelete]
        public async Task<IActionResult> Delete(int id)
        {
            var imageSliderObj = await _unitOfWork.ImageSlider.GetAsync(id);
            if (imageSliderObj == null)
            {
                return Json(new { success = false, message = "Error While Deleting" });
            }
            var webRootPath = _webHostEnveronment.WebRootPath;
            var imageData = Path.Combine(webRootPath, imageSliderObj.ImageUrl.TrimStart('\\'));
            if (System.IO.File.Exists(imageData))
            {
                System.IO.File.Delete(imageData);
            }
            await _unitOfWork.ImageSlider.RemoveAsync(imageSliderObj);
            await _unitOfWork.SaveAsync();
            return Json(new { success = true, message = "Deleted Successfully" });
        }
        #endregion
    }

}

ElectricStore/Areas/Customer/Controllers/ShopController.cs
using ElectricStore.DataAccess.IRepository;
using ElectricStore.Models.Models;
using ElectricStore.Models.ViewModels;
using ElectricStore.Utility;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ElectricStore.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class ShopController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        public ShopController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index(string search, int minimumPrice, int maximumPrice, int categoryID,int brandId, int sortBy, int? pageNo)
        {
            var pageSize = 5;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo : 1 : 1;
            var totalProduct = await _unitOfWork.Product.CountAsync(search: search, categoryId: categoryID,brandId:brandId, maximum: maximumPrice,
                minimum: minimumPrice, sortBy: sortBy);
            ShopIndexVM shopIndexVM = new ShopIndexVM()
            {
                CategoryList = await _unitOfWork.Category.GetAllAsync(),
                BrandList = await _unitOfWork.Brand.GetAllAsync(),
                MaximumPrice = await _unitOfWork.Product.Maximum(),
                MinimumPrice = minimumPrice,
                CategoryId = categoryID,
                BrandId=brandId,
                SortById = sortBy,
                Search = search,
                ProductList = await _unitOfWork.Product.GetAllAsync(includeProperties: "Category,Brand"),
                Pager = new Pager(totalProduct, pageNo, pageSize)
            };
            return View(shopIndexVM);
        }
        public async Task<IActionResult> ProductList(string search, int minimumPrice, int maximumPrice, int categoryID,int brandId, int sortBy, int? pageNo)
        {
            var pageSize = 5;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo : 1 : 1;
            var totalProduct = await _unitOfWork.Product.
                CountAsync(search: search, categoryId: categoryID, maximum: maximumPrice,
                minimum: minimumPrice, sortBy: sortBy);
            ShopVM shopVM = new ShopVM()
            {
                ProductList = await _unitOfWork.Product.
                SearchAsync(pageNumber: pageNo.Value, pageSize: pageSize, search: search, categoryId: categoryID,brandId:brandId, maximum: maximumPrice,
                minimum: minimumPrice, sortBy: sortBy),
                MaximumPrice = maximumPrice,
                MinimumPrice = minimumPrice,
                BrandId=brandId,
                Search = search,
                CategoryId = categoryID,
                SortById = sortBy,
                Pager = new Pager(totalProduct, pageNo, pageSize)
            };
            return PartialView(shopVM);
        }

    }
}

ElectricStore/Areas/Identity/Pages/Account/AccessDenied.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace ElectricStore.Areas.Identity.Pages.Account
{
    public class AccessDeniedModel : PageModel
    {
        public void OnGet()
        {

        }
    }
}

ElectricStore/Views/Shared/AccessDenied.cshtml
@{
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container" id="main-container">
    <div class="text-center">
        <h2 class="text-danger">You have no access in this Section</h2>
    </div>

</div>


@section Scripts{
    <script>
    $(".loader").fadeOut(1000);
    $(".wrapper").fadeIn(1000);
    </script>
}

ElectricStore/Views/Shared/_CreateAndBackToList.cshtml
<div class="row">
    <div class="col">
        <input type="submit" class="btn btn-primary form-control"  value="Create" />
    </div>
    <div class="col">
        <a class="btn btn-success form-control" asp-action="Index">Back To List</a>
    </div>

</div>

ElectricStore/Views/Shared/_EditAndBackToList.cshtml
<div class="row">
    <div class="col">
        <input type="submit" class="btn btn-primary form-control" asp-route-id="@Model" value="Update"  />
    </div>
    <div class="col">
        <a  class="btn btn-success form-control" asp-action="Index">Back To List</a>
    </div>

</div>

ElectricStore/Views/Shared/_Layout.cshtml
@using ElectricStore.Utility
@using Microsoft.AspNetCore.Http
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager
@inject IHttpContextAccessor  HttpContextAccessor
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - ElectricBazar</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="https://cdn.datatables.net/1.10.16/css/jquery.dataTables.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/css/toastr.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-primary border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand text-white" asp-area="" asp-controller="Home" asp-action="Index">ElectricStore</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Customer" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-white" asp-area="Customer" asp-controller="Shop" asp-action="Index">Shop</a>
                        </li>

                        @if (User.IsInRole("Admin"))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Content Management
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Category" asp-action="Index">Category</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Brand" asp-action="Index">Brand</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Product" asp-action="Index">Product</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Slider" asp-action="Index">Slider</a>

                                    <a class="dropdown-item" href="#">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                            <li class="nav-item dropdown">
                                <a class="nav-link text-white dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    User/Role 
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="User" asp-action="Index">User</a>
                                    <a class="dropdown-item" asp-area="Admin" asp-controller="Role" asp-action="Index">Role</a>
                                    <a class="dropdown-item" href="#">Another action</a>
                                    <div class="dropdown-divider"></div>
                                    <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>
                        }
                        @if (SignInManager.IsSignedIn(User))
                        {

                            <li class="nav-item">
                                <a class="nav-link text-white" asp-area="Admin" asp-controller="Order" asp-action="Index">
                                    @if (User.IsInRole("Admin"))
                                    {
                                        <span>Manage Order</span>
                                    }
                                    else
                                    {
                                        <span>Order History</span>
                                    }
                                </a>
                            </li>
                        }
                            @if (HttpContextAccessor.HttpContext.Session.GetInt32(SD.ShoppingCart) != null)
                            {
                                <li style="color:white" class="nav-item">
                                    <a asp-area="Customer" asp-controller="Cart" asp-action="Index" class="nav-link text-white">
                                        @{
                                            var count = HttpContextAccessor.HttpContext.Session.GetInt32(SD.ShoppingCart);
                                        }
                                        <i class="fas fa-shopping-cart">&nbsp; (@count) </i>

                                    </a>

                                </li>
                            }
                            else
                            {
                                <li class="nav-item">
                                    <a href="#" class="nav-link text-white">

                                        <i class="fas fa-shopping-cart">&nbsp; (0) </i>
                                    </a>

                                </li>
                            }
                        </ul>
                    <partial name="_LoginPartial" />
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    
    
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/jqueryui/1.12.1/jquery-ui.min.js"></script>
    <script src="https://cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/toastr.js/latest/js/toastr.min.js"></script>
    <script src="https://unpkg.com/sweetalert/dist/sweetalert.min.js"></script>
    <script src="https://kit.fontawesome.com/e19c476714.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>