ElectricStore/Areas/Customer/Controllers/HomeController.cs
using ElectricStore.Data;
using ElectricStore.DataAccess.IRepository;
using ElectricStore.Models;
using ElectricStore.Models.Models;
using ElectricStore.Models.ViewModels;
using ElectricStore.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace ElectricStore.Controllers
{
    [Area("Customer")]
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly IUnitOfWork _unitOfWork;
        private readonly ApplicationDbContext _db;
        public HomeController(ILogger<HomeController> logger,IUnitOfWork unitOfWork,
            ApplicationDbContext db)
        {
            _logger = logger;
            _unitOfWork = unitOfWork;
            _db = db;
        }
        [Route("")]
        public async Task<IActionResult> Index()
        {

            HomeVM homeVM = new HomeVM()
            {
                Product = await _unitOfWork.Product.GetAllAsync(includeProperties: "Category,Brand"),
                Brand=await _unitOfWork.Brand.GetAllAsync(),
                Category=await _unitOfWork.Category.GetAllAsync(),
                ImageSlider=await _unitOfWork.ImageSlider.GetAllAsync()
            };
          
            var claimsIdentoity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentoity.FindFirst(ClaimTypes.NameIdentifier);
            if (claim != null)
            {
                var objList = await _unitOfWork.ShoppingCart.
                    GetAllAsync(x => x.ApplicationUserId == claim.Value);
                var count = objList.ToList().Count();
                HttpContext.Session.SetInt32(SD.ShoppingCart, count);
            }
            return View(homeVM);
        }

        public IActionResult Privacy()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> Details(int id)
        {
            var productObj = await _unitOfWork.Product.FirstOrDefaultAsync(x => x.Id == id, includeProperties: "Category,Brand");

            ShoppingCart cartObj = new ShoppingCart()
            {
                Product = productObj,
                ProductId = productObj.Id
            };

            return View(cartObj);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize]
        public async Task<IActionResult> Details(ShoppingCart shoppingCart)
        {
            shoppingCart.Id = 0;
            if (ModelState.IsValid)
            {
                var claimsIdentity = (ClaimsIdentity)User.Identity;
                var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
                shoppingCart.ApplicationUserId = claim.Value;

                ShoppingCart cartObj = await _unitOfWork.ShoppingCart.
                    FirstOrDefaultAsync(x => x.ApplicationUserId == shoppingCart.ApplicationUserId
                    && x.ProductId == shoppingCart.ProductId, includeProperties: "Product");
                if (cartObj == null)
                {
                    await _unitOfWork.ShoppingCart.AddAsync(shoppingCart);
                }
                else
                {
                    cartObj.Count += shoppingCart.Count;
                    await _unitOfWork.ShoppingCart.UpdateAsync(cartObj);
                }

                await _unitOfWork.SaveAsync();
                var count = await _unitOfWork.ShoppingCart.GetAllAsync(x => x.ApplicationUserId == shoppingCart.ApplicationUserId);
                var objNumber = count.Count();
                HttpContext.Session.SetInt32(SD.ShoppingCart, objNumber);
                return RedirectToAction(nameof(Index));
            }
            else
            {
                var productObj = await _unitOfWork.Product.FirstOrDefaultAsync(x => x.Id == shoppingCart.Id,
                    includeProperties: "Category,Brand");
                ShoppingCart cartobj = new ShoppingCart()
                {
                    Product = productObj,
                    ProductId = productObj.Id,
                };
                return View(cartobj);
            }
        }
        public async Task<IActionResult> RemoveFormCart(int id)
        {
            var claimsIdentity = (ClaimsIdentity)User.Identity;
            var claim = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            var objDb = await _unitOfWork.ShoppingCart.FirstOrDefaultAsync(x => x.Id == id);
            if (objDb != null)
            {
                await _unitOfWork.ShoppingCart.RemoveAsync(objDb);
            }
            var objList = await _unitOfWork.ShoppingCart.GetAllAsync(x => x.ApplicationUserId == claim.Value);
            var count = objList.Count();
            HttpContext.Session.SetInt32(SD.ShoppingCart, count);
            return RedirectToAction(nameof(Index));
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }



    }
}

ElectricStore/ViewComponents/RelatedProductViewComponent.cs
using ElectricStore.Data;
using ElectricStore.DataAccess.IRepository;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ElectricStore.ViewComponents
{
    public class RelatedProductViewComponent:ViewComponent
    {

        private readonly IUnitOfWork _unitOfWork;
        private readonly ApplicationDbContext _db;

        public RelatedProductViewComponent(IUnitOfWork unitOfWork, ApplicationDbContext db)
        {
            _unitOfWork = unitOfWork;
            _db = db;
        }

        public async Task<IViewComponentResult> InvokeAsync(int id)
        {
           
            var productList = await _unitOfWork.Product.GetAllAsync(x=>x.CategoryId==id,includeProperties:"Category,Brand");
            return View(productList);
        }
    }
}

ElectricStore/Areas/Customer/Views/Home/Details.cshtml
@model ElectricStore.Models.Models.ShoppingCart
@{
    ViewData["Title"] = "Details";
    Layout = "~/Views/Shared/_Layout.cshtml";
}


<form method="post" asp-action="Details">
    <input hidden asp-for="ProductId" />
    <div class="container backgroundWhite">
        <div class="card">
            <div class="card-header bg-light text-light ml-0 row container">
                <div class="col-12 col-md-6">
                    <h1 class="text-primary">@Model.Product.Name</h1>
                    
                </div>
                <div class="col-12 col-md-6 text-md-right pt-4">
                    <span class="badge badge-success pt-2" style="height:30px;">@Model.Product.Brand.Name</span>
                    <span class="badge badge-warning pt-2" style="height:30px;">@Model.Product.Category.Name</span>
                </div>
            </div>
            <div class="card-body">
                <div class="container rounded p-2">
                    <div class="row">
                        <div class="col-8 col-lg-8">

                            <div class="row pl-2">
                                <h5 class="text-muted">ISBN : @Model.Product.Code</h5>
                            </div>
                            <div class="row pl-2">
                                <h5 class="text-muted pb-2">List Price: <strike>@Model.Product.Price.ToString("c")</strike></h5>
                            </div>
                            <div class="row text-center pl-2">
                                <div class="p-1 col-2 bg-secondary border-bottom">
                                    <div>Quantity</div>
                                </div>
                                <div class="p-1 col-2 bg-secondary border-bottom">
                                    <div>Regular Price </div>
                                </div>
                                <div class="p-1 col-2 bg-secondary border-bottom">
                                    <div>DisCount Price</div>
                                </div>
                                
                            </div>
                            <div class="row text-center pl-2" style="color:maroon; font-weight:bold">
                                <div class="p-1 col-2 bg-secondary">
                                    <div>Price</div>
                                </div>
                                <div class="p-1 col-2 bg-secondary">
                                    <div>@Model.Product.Price.ToString("c")</div>
                                </div>
                                <div class="p-1 col-2 bg-secondary">
                                    <div>@Model.Product.DiscountPrice</div>
                                </div>
                                
                            </div>
                            <div class="row pl-2">
                                <p class="text-secondary">@Html.Raw(Model.Product.Description)</p>
                            </div>
                            
                        </div>
                        <div class="col-12 col-lg-3 offset-lg-1 text-center">
                            <img src="@Model.Product.ImageUrl" width="100%" class="rounded" />
                        </div>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <div class="row">
                    <div class="col-12 col-md-6 pb-1">
                        <a asp-action="Index"  class="btn btn-success form-control  btn-square btn-lg" style="height:50px;">Back to List</a>
                    </div>
                    <div class="col-12 col-md-6 pb-1">
                        <button type="submit" value="Add to Cart" class="btn btn-primary btn-square btn-lg form-control" style="height:50px;">Add to Cart</button>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>

<div class="container">
    <div class="row">
        <div class="col-12">
            <h1>Related Products</h1>
        </div>
        
        <div class="col-12">
            @await Component.InvokeAsync("RelatedProduct", new { id=Model.Product.CategoryId });
        </div>

    </div>

</div>

ElectricStore/Areas/Customer/Views/Home/Index.cshtml
@model ElectricStore.Models.ViewModels.HomeVM

@{
    ViewData["Title"] = "Home Page";
}

<div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
        <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
        <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" style="height:75vh;">
        <div class="carousel-item active">
            <img class="d-block w-100 " src="./Photos/Slider/ad839cc1-d308-4393-9c8a-65119c8c8e76.jpg" alt="First slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100 " src="./Photos/Slider/d169e87e-a2fe-440d-9fbe-0f16795a469d.jpg" alt="Second slide">
        </div>
        <div class="carousel-item">
            <img class="d-block w-100 " src="./Photos/Slider/dd3bba9c-45c9-445f-9d0f-59de12e6ea86.jpg" alt="Third slide">
        </div>
    </div>
    <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
        <span class="carousel-control-prev-icon" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
        <span class="carousel-control-next-icon" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="container pr-3">

    <img src="~/Photos/Services.PNG" class="w-100" />

</div>
<div class="container" >
    <div class="row">
        <div class="col-5 m-4 p-3" style="background-color:whitesmoke";>
            <h1 class="p-4 text-center">New Products</h1>
            <div style="height:100px">

                @foreach (var item in Model.Product)
                {
                    <a asp-controller="Home" asp-action="Details" asp-route-id="@item.Id" >
                        <div class="row p-3 mb-1" style="border:1px solid #000000">
                            <div class="col-3">
                                <span>@item.Name</span>
                            </div>
                            <div class="col-3">
                                <span>@item.Category.Name</span>
                            </div>
                            <div class="col-3">
                                <span>@item.Price</span>
                            </div>
                            <div class="col-3">
                                <img src="@item.ImageUrl" width="80" height="80" />
                            </div>
                        </div>
                </a>
                 
                
                   }
           </div>       
        </div>
        <div class="col-5 m-4 p-3 mr-auto" style="background-color:whitesmoke" ;>
            <h1 class="p-4 text-center">Fetured  Products</h1>
            <div style="height:100px">

                @foreach (var item in Model.Product)
                {
                    <a asp-controller="Home" asp-action="Details" asp-route-id="@item.Id">
                        <div class="row p-3 mb-1" style="border:1px solid #000000">
                            <div class="col-3">
                                <span>@item.Name</span>
                            </div>
                            <div class="col-3">
                                <span>@item.Category.Name</span>
                            </div>
                            <div class="col-3">
                                <span>@item.Price</span>
                            </div>
                            <div class="col-3">
                                <img src="@item.ImageUrl" width="80" height="80" />
                            </div>
                        </div>
                    </a>
                }
            </div>
        </div>
    </div>
</div>