ElectricStore/Areas/Customer/Controllers/ShopController.cs
using ElectricStore.DataAccess.IRepository;
using ElectricStore.Models.Models;
using ElectricStore.Models.ViewModels;
using ElectricStore.Utility;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ElectricStore.Areas.Customer.Controllers
{
    [Area("Customer")]
    public class ShopController : Controller
    {

        private readonly IUnitOfWork _unitOfWork;
        public ShopController(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IActionResult> Index(string search, int minimumPrice, int maximumPrice, int categoryID,int brandId, int sortBy, int? pageNo)
        {
            var pageSize = 5;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo : 1 : 1;
            var totalProduct = await _unitOfWork.Product.CountAsync(search: search, categoryId: categoryID,brandId:brandId, maximum: maximumPrice,
                minimum: minimumPrice, sortBy: sortBy);
            ShopIndexVM shopIndexVM = new ShopIndexVM()
            {
                CategoryList = await _unitOfWork.Category.GetAllAsync(),
                BrandList = await _unitOfWork.Brand.GetAllAsync(),
                MaximumPrice = await _unitOfWork.Product.Maximum(),
                MinimumPrice = minimumPrice,
                CategoryId = categoryID,
                BrandId=brandId,
                SortById = sortBy,
                Search = search,
                ProductList = await _unitOfWork.Product.GetAllAsync(includeProperties: "Category,Brand"),
                Pager = new Pager(totalProduct, pageNo, pageSize)
            };
            return View(shopIndexVM);
        }
        public async Task<IActionResult> ProductList(string search, int minimumPrice, int maximumPrice, int categoryID,int brandId, int sortBy, int? pageNo)
        {
            var pageSize = 5;
            pageNo = pageNo.HasValue ? pageNo.Value > 0 ? pageNo : 1 : 1;
            var totalProduct = await _unitOfWork.Product.
                CountAsync(search: search, categoryId: categoryID, maximum: maximumPrice,
                minimum: minimumPrice, sortBy: sortBy);
            ShopVM shopVM = new ShopVM()
            {
                ProductList = await _unitOfWork.Product.
                SearchAsync(pageNumber: pageNo.Value, pageSize: pageSize, search: search, categoryId: categoryID,brandId:brandId, maximum: maximumPrice,
                minimum: minimumPrice, sortBy: sortBy),
                MaximumPrice = maximumPrice,
                MinimumPrice = minimumPrice,
                BrandId=brandId,
                Search = search,
                CategoryId = categoryID,
                SortById = sortBy,
                Pager = new Pager(totalProduct, pageNo, pageSize)
            };
            return PartialView(shopVM);
        }

    }
}

ElectricStore/ViewComponents/CategoryViewComponent.cs
using ElectricStore.DataAccess.IRepository;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace ElectricStore.ViewComponents
{
    public class CategoryViewComponent:ViewComponent
    {
        private readonly IUnitOfWork _unitOfWork;

        public CategoryViewComponent(IUnitOfWork unitOfWork)
        {
            _unitOfWork = unitOfWork;
        }

        public async Task<IViewComponentResult> InvokeAsync()
        {
            //    var claimsIdentity = (ClaimsIdentity)User.Identity;
            //    var claims = claimsIdentity.FindFirst(ClaimTypes.NameIdentifier);
            //    var userFromDb = _unitOfWork.ApplicationUser.GetFirstOrDefault(u => u.Id == claims.Value);
            var categoryList = await _unitOfWork.Category.GetAllAsync();
            return View(categoryList);
        }
    }
}

ElectricStore/Areas/Customer/Views/Shop/GetCategory.cshtml
@model IEnumerable<ElectricStore.Models.Models.Product>
@{
    ViewData["Title"] = "GetCategory";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="row p-5">
    <div class="col-3">
        @await Component.InvokeAsync("Category")
    </div>
    <div class="col-9">
        @foreach (var item in Model)
        {
        <div class="row">
            <div class="col-lg-3 col-md-6">
                <div class="row p-2">
                    <div class="col-12 text-center  p-1" style="border:1px solid #008cba; border-radius: 5px;">
                        <div class="card" style="border:0px;">
                            <img src="@item.ImageUrl" class="card-img-top rounded" />
                            <div class="pl-1">
                                <p class="card-title h5"><b style="color:#2c3e50">@item.Name</b></p>
                                <p class="card-title text-primary">by <b>@item.Code</b></p>
                            </div>
                            <div style="padding-left:5px;">
                                <p>List Price: <strike><b class="">$@item.Price</b></strike></p>
                            </div>
                            <div style="padding-left:5px;">
                                <p style="color:maroon">As low as: <b class="">$@item.DiscountPrice</b></p>
                            </div>
                        </div>
                        <div>
                            <a asp-action="Details" asp-route-id="@item.Id" class="btn btn-primary form-control text-center">Detials</a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        
        }
    </div>

</div>

ElectricStore/Areas/Customer/Views/Shop/Index.cshtml
@using ElectricStore.Models.ViewModels
@model ElectricStore.Models.ViewModels.ShopIndexVM
@using ElectricStore.DataAccess.Data

@{
    ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<div class="container">
    <h1 class="text-center border-bottom">Shop</h1>


    <br />
    <div class="row">
        <div class="col-4 p-2">
            <div class="row">
                <div class="col-12">
                    <input class="form-control" id="search" value="@Model.Search" placeholder="Search.." />
                </div>
                <div class="col-12 my-2" id="sort">
                    <h3>Sort By</h3>
                    <ul class="list-group">
                        <li class="list-group-item sortBy " style="cursor:pointer;"><a data-href="@Url.Action("ProductList", "Shop", new { sortBy = (int)SortByEnum.Default})" class="dataLink">Default - Newest</a></li>
                        <li class="list-group-item sortBy " style="cursor:pointer;"><a data-href="@Url.Action("ProductList", "Shop", new { sortBy = (int)SortByEnum.Popularity  })" class="dataLink">Popularity</a></li>
                        <li class="list-group-item sortBy " style="cursor:pointer;"><a data-href="@Url.Action("ProductList", "Shop", new { sortBy = (int)SortByEnum.LowtoHighPrice})" class="dataLink">Price: low to high</a></li>
                        <li class="list-group-item  sortBy" style="cursor:pointer;"><a data-href="@Url.Action("ProductList", "Shop", new { sortBy = (int)SortByEnum.HightoLowPrice  })" class="dataLink">Price: high to low</a></li>
                    </ul>
                </div>

                <div class="col-12 my-2">
                    <h3>Category</h3>
                    <div class="tag-list" id="category">
                        <ul class="list-group">
                            <li class="list-group-item categoryId" style="cursor:pointer;">
                                <a data-href="@Url.Action("ProductList", "Shop", new { categoryID = 0})" class="categorydataLink @((int)Model.CategoryId == 0 ? "active" : string.Empty)">All</a>
                            </li>
                            @foreach (var category in Model.CategoryList)
                            {
                                <li class="list-group-item categoryId" style="cursor:pointer;">
                                    <a data-href="@Url.Action("ProductList", "Shop", new { categoryID = category.Id})" class="categorydataLink @((int)Model.CategoryId == category.Id ? "active" : string.Empty)">@category.Name</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
                <div class="col-12 my-2">
                    <h3>Brand</h3>
                    <div class="tag-list" id="brand">
                        <ul class="list-group">
                            <li class="list-group-item brandId" style="cursor:pointer;">
                                <a data-href="@Url.Action("ProductList", "Shop", new { brandId = 0})" class="branddataLink @((int)Model.BrandId == 0 ? "active" : string.Empty)">All</a>
                            </li>
                            @foreach (var brand in Model.BrandList)
                            {
                                <li class="list-group-item brandId" style="cursor:pointer;">
                                    <a data-href="@Url.Action("ProductList", "Shop", new { brandId = brand.Id})" class="branddataLink @((int)Model.BrandId == brand.Id ? "active" : string.Empty)">@brand.Name</a>
                                </li>
                            }
                        </ul>
                    </div>
                </div>
                <div class="widget widget-price col-12 my-2">
                    <h5 class="widget-title">Filter by price</h5>
                    <div class="price-filter">
                        <div id="slide-range"></div>
                        <p class="amount">
                            Price: <input type="text"  id="amount" disabled="">
                        </p>
                    </div>
                </div>

            </div>

        </div>
        <div class="col-8" id="container">
            @{
                ShopVM shopVM = new ShopVM()
                {
                    ProductList = Model.ProductList,
                    Pager = Model.Pager,
                    CategoryId = Model.CategoryId,
                    BrandId=Model.BrandId,
                    SortById = Model.SortById,
                    MaximumPrice = Model.MaximumPrice,
                    MinimumPrice = Model.MinimumPrice,
                    Search = Model.Search
                };
                <partial name="ProductList" model="shopVM" />
            }
            <label id="text"></label>
            <label id="text1"></label>
        </div>
    </div>
</div>

@section Scripts{
    <script>

        $('#sort li').click(function (e) {
                $(this).addClass('active').siblings().removeClass('active');
        });
        $('#category li').click(function (e) {
            $(this).addClass('active').siblings().removeClass('active');
        });
        $('#brand li').click(function (e) {
            $(this).addClass('active').siblings().removeClass('active');
        });


    </script>

    <script>
        $(document).ready(function () {
            $("#search").keyup(function () {
                $.ajax({
                    url: '@Url.Action("ProductList", "Shop")',
                    data: {
                        search: $("#search").val(),
                        sortBy: $("#SortBy").val(),
                        categoryID: $("#CategoryId").val(),
                        brandId: $("#brandId").val(),
                        minimumPrice: priceSlider.slider("values", 0),
                        maximumPrice: priceSlider.slider("values", 1),
                    }
                })
                    .done(function (response) {
                        $("#container").html(response);
                    })
                    .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                        alert("FAIL");
                    });
            });
            $("#resetBtn").click(function () {
                var searchValue = "";
                $("#search").val('');
                $.ajax({
                    url: '@Url.Action("CategoryTable", "Category")',
                    data: {
                        search: searchValue
                    }
                })
                    .done(function (response) {
                        $("#container").html(response);
                    })
                    .fail(function (XMLHttpRequest, textStatus, errorThrown) {
                        alert("FAIL");
                    });
            });
          });
    </script>
    <script>

	var callTimeout;
	var priceSlider = $("#slide-range").slider({
		range: true,
		min: 0,
		max: '@Model.MaximumPrice',
		values: [0, @Model.MaximumPrice],
		slide: function (event, ui) {
			var minPrice = ui.values[0];
			var maxPrice = ui.values[1];

			$("#amount").val("$" + minPrice + ".00" + " - " + "$" + maxPrice + ".00");

			clearTimeout(callTimeout);
			callTimeout = setTimeout(PriceRangeChange, 500);
		}
	});

        $(".dataLink").click(function () {

        var url = $(this).attr("data-href");
        console.log(url);



		if (url != "" || url != undefined) {
			GetData(url);
		}
        });

        $(".categorydataLink").click(function () {

            var url = $(this).attr("data-href");

            console.log(url);
            if (url != "" || url != undefined) {
                GetData(url);
            }
        });
        $(".branddataLink").click(function () {

            var url = $(this).attr("data-href");

            console.log(url);
            if (url != "" || url != undefined) {
                GetData(url);
            }
        });

	function GetData(dUrl){
		console.log("getdata in");


		$.ajax({
			url: dUrl,
            data: {
                search: $("#SearchTerm").val(),
                sortBy: $("#SortBy").val(),
                categoryID: $("#CategoryID").val(),

				minimumPrice : priceSlider.slider("values", 0),
                maximumPrice: priceSlider.slider("values", 1),
			}
		})
        .done(function (response) {
        	console.log("done");
        	$("#container").html(response);
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	console.log("fail");
        	alert("FAIL");
        })
    };
	function PriceRangeChange(){
		$.ajax({
			url: '@Url.Action("ProductList", "Shop")',
			data: {
				search: $("#SearchTerm").val(),
                sortBy: $("#SortBy").val(),
                brandId: $("#brandId").val(),
				categoryID: $("#CategoryID").val(),
				minimumPrice : priceSlider.slider("values", 0),
				maximumPrice : priceSlider.slider("values", 1)
			}
		})
        .done(function (response) {
            $("#container").html(response);
            console.log("Get");
        })
        .fail(function (XMLHttpRequest, textStatus, errorThrown) {
        	alert("FAIL");
        });
    };
    </script>
}

ElectricStore/Areas/Customer/Views/Shop/ProductList.cshtml
@model ElectricStore.Models.ViewModels.ShopVM
@using ElectricStore.Models.ViewModels


<div class="container mydiv">
    <div class="row" id="bookList">
        @foreach (var item in Model.ProductList)
        {
            <div class="col-lg-4 col-md-6 col-sm-12">
                <div class="row p-2">
                    <div class="col-12  p-1" style="border:1px solid #008cba; border-radius: 5px;">
                        <div class="card" style="border:0px;">
                            <img src="@item.ImageUrl" class="card-img-top rounded" />
                            <div class="pl-1">
                                <p class="card-title h5"><b style="color:#2c3e50">@item.Name</b></p>
                                <p class="card-title text-primary">by <b>@item.Brand.Name</b></p>
                            </div>
                            <div style="padding-left:5px;">
                                <p>List Price: <strike><b class="">@item.Price</b></strike></p>
                            </div>
                            @if (item.DiscountPrice != 0 && item.DiscountPrice != null)
                            {
                                <div style="padding-left:5px;">
                                    <p style="color:maroon">As low as: <b class="">@item.DiscountPrice</b></p>
                                </div>
                            }
                            <div style="padding-left:5px;">
                                <p  style="color:maroon">As low as: <b class="">@item.Price</b></p>
                            </div>

                        </div>
                        <div class="text-center">
                            <a asp-controller="Home" asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-primary form-control">View Details</a>
                        </div>
                    </div>
                </div>
            </div>
          
        
        }

    </div>
</div>
<br />
<div>
    @if (Model.Pager != null && Model.Pager.TotalPages > 1)
    {
        <ul class="pagination">
            @if (Model.Pager.CurrentPage > 1)
            {
                <li class="prev page-item " style="cursor:pointer;">
                    <a data-href="@Url.Action("ProductList", "Shop", new { pageNo = Model.Pager.CurrentPage - 1, sortBy = Model.SortById, categoryID = Model.CategoryId,search=Model.Search,maximumPrice=Model.MaximumPrice,minimumPrice=Model.MinimumPrice })" class="pageDataLink page-link"><i class="fa fa-angle-left"></i></a>
                </li>
            }

            @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;
                <li style="cursor:pointer;" class="@activeClass pointer-event  page-item"><a data-href="@Url.Action("ProductList", "Shop", new { pageNo = page, sortBy = Model.SortById, categoryID = Model.CategoryId,search=Model.Search,maximumPrice=Model.MaximumPrice,minimumPrice=Model.MinimumPrice  })" class="pageDataLink page-link">@(page)</a></li>
            }

            @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <li style="cursor:pointer;" class="page-item pointer-event "><a data-href="@Url.Action("ProductList", "Shop", new { pageNo = Model.Pager.CurrentPage + 1, sortBy = Model.SortById, categoryID = Model.CategoryId,search=Model.Search,maximumPrice=Model.MaximumPrice,minimumPrice=Model.MinimumPrice })" class="pageDataLink page-link"><i class="fa fa-angle-right"></i></a></li>
            }
        </ul>
    }
</div>

@*@{ 
    ShopIndexVM shopIndexVM = new ShopIndexVM()
    {
        CategoryId = Model.CategoryId,
        SortById = Model.SortById,
        Search = Model.Search
    };
    TempData["ID"] = shopIndexVM;
}*@

<input hidden id="SearchTerm" value="@Model.Search" />

<input hidden id="SortBy" value="@Model.SortById" />

<input hidden id="CategoryID" value="@Model.CategoryId" />



<script>
    $(document).ready(function () {
        $(".pageDataLink").click(function () {
            var url = $(this).attr("data-href");

            console.log(url);

            if (url != "" || url != undefined) {
                GetData(url);
            }
        });
    });

</script>

ElectricStore/Areas/Customer/Views/Shop/_ShopPartial.cshtml
@model ElectricStore.Models.ViewModels.ShopVM
@using ElectricStore.Models.ViewModels


<div class="container mydiv">
    <div class="row" id="bookList">
        @foreach (var item in Model.ProductList)
        {
        <div class="col-lg-4 col-md-6 col-sm-12">
            <div class="row p-2">
                <div class="col-12  p-1" style="border:1px solid #008cba; border-radius: 5px;">
                    <div class="card" style="border:0px;">
                        <img src="@item.ImageUrl" class="card-img-top rounded" />
                        <div class="pl-1">
                            <p class="card-title h5"><b style="color:#2c3e50">@item.Name</b></p>
                            <p class="card-title text-primary">by <b>@item.Brand.Name</b></p>
                        </div>
                        <div style="padding-left:5px;">
                            <p>List Price: <strike><b class="">@item.Price</b></strike></p>
                        </div>
                        @if (item.DiscountPrice != 0 && item.DiscountPrice != null)
                        {
                            <div style="padding-left:5px;">
                                <p style="color:maroon">As low as: <b class="">@item.DiscountPrice</b></p>
                            </div>
                        }
                        <div style="padding-left:5px;">
                            <p style="color:maroon">As low as: <b class="">@item.Price</b></p>
                        </div>
                    </div>
                    <div class="text-center">
                        <a asp-controller="Home" asp-action="Details" asp-route-id="@item.Id" class="btn btn-sm btn-primary form-control">View Details</a>
                    </div>
                </div>
            </div>
        </div>      
        }
    </div>
</div>
<br />
<div>
    @if (Model.Pager != null && Model.Pager.TotalPages > 1)
    {
        <ul class="pagination">
            @if (Model.Pager.CurrentPage > 1)
            {
                <li class="prev page-item " style="cursor:pointer;">
                    <a data-href="@Url.Action("ProductList", "Shop", new { pageNo = Model.Pager.CurrentPage - 1, sortBy = Model.SortById, categoryID = Model.CategoryId })" class="pageDataLink page-link"><i class="fa fa-angle-left"></i></a>
                </li>
            }

            @for (var page = Model.Pager.StartPage; page <= Model.Pager.EndPage; page++)
            {
                string activeClass = Model.Pager.CurrentPage == page ? "active bg-info" : string.Empty;

                <li style="cursor:pointer;" class="@activeClass pointer-event  page-item"><a data-href="@Url.Action("ProductList", "Shop", new { pageNo = page, sortBy = Model.SortById, categoryID = Model.CategoryId })" class="pageDataLink page-link">@(page)</a></li>
            }

            @if (Model.Pager.CurrentPage < Model.Pager.TotalPages)
            {
                <li style="cursor:pointer;" class="page-item pointer-event "><a data-href="@Url.Action("ProductList", "Shop", new { pageNo = Model.Pager.CurrentPage + 1, sortBy = Model.SortById, categoryID = Model.CategoryId})" class="pageDataLink page-link"><i class="fa fa-angle-right"></i></a></li>
            }
        </ul>
    }
</div>


<input hidden id="SearchTerm" value="@Model.Search" />

<input hidden id="SortBy" value="@Model.SortById" />

<input hidden id="CategoryID" value="@Model.CategoryId" />
<input hidden id="CategoryID" value="@Model.BrandId" />


<script>
    $(document).ready(function () {
        $(".pageDataLink").click(function () {
            var url = $(this).attr("data-href");

            console.log(url);

            if (url != "" || url != undefined) {
                GetData(url);
            }
        });
    });

</script>